/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiongliang_ffmpegpratice_Metadata */

#ifndef _Included_com_xiongliang_ffmpegpratice_Metadata
#define _Included_com_xiongliang_ffmpegpratice_Metadata
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiongliang_ffmpegpratice_Metadata
 * Method:    metadata
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xiongliang_ffmpegpratice_Metadata_metadata
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
