/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiongliang_ffmpegpratice_EncodeAudio */

#ifndef _Included_com_xiongliang_ffmpegpratice_EncodeAudio
#define _Included_com_xiongliang_ffmpegpratice_EncodeAudio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiongliang_ffmpegpratice_EncodeAudio
 * Method:    encodeAudio
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xiongliang_ffmpegpratice_EncodeAudio_encodeAudio
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
