/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiongliang_ffmpegpratice_Resample */

#ifndef _Included_com_xiongliang_ffmpegpratice_Resample
#define _Included_com_xiongliang_ffmpegpratice_Resample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiongliang_ffmpegpratice_Resample
 * Method:    resample
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xiongliang_ffmpegpratice_Resample_resample
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
