/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiongliang_ffmpegpratice_Muxing */

#ifndef _Included_com_xiongliang_ffmpegpratice_Muxing
#define _Included_com_xiongliang_ffmpegpratice_Muxing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiongliang_ffmpegpratice_Muxing
 * Method:    muxing
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xiongliang_ffmpegpratice_Muxing_muxing
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
