/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiongliang_ffmpegpratice_ScaleVideo */

#ifndef _Included_com_xiongliang_ffmpegpratice_ScaleVideo
#define _Included_com_xiongliang_ffmpegpratice_ScaleVideo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiongliang_ffmpegpratice_ScaleVideo
 * Method:    scaleVideo
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xiongliang_ffmpegpratice_ScaleVideo_scaleVideo
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
