/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiongliang_ffmpegpratice_EncodeVideo */

#ifndef _Included_com_xiongliang_ffmpegpratice_EncodeVideo
#define _Included_com_xiongliang_ffmpegpratice_EncodeVideo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiongliang_ffmpegpratice_EncodeVideo
 * Method:    encodeVideo
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xiongliang_ffmpegpratice_EncodeVideo_encodeVideo
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
