/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiongliang_ffmpegpratice_DecodeVideo */

#ifndef _Included_com_xiongliang_ffmpegpratice_DecodeVideo
#define _Included_com_xiongliang_ffmpegpratice_DecodeVideo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiongliang_ffmpegpratice_DecodeVideo
 * Method:    devodeVideo
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xiongliang_ffmpegpratice_DecodeVideo_devodeVideo
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
