/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiongliang_ffmpegpratice_DemuxAndDecode */

#ifndef _Included_com_xiongliang_ffmpegpratice_DemuxAndDecode
#define _Included_com_xiongliang_ffmpegpratice_DemuxAndDecode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiongliang_ffmpegpratice_DemuxAndDecode
 * Method:    demuxAndDecode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xiongliang_ffmpegpratice_DemuxAndDecode_demuxAndDecode
        (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
