/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiongliang_ffmpegpratice_DecodeAudio */

#ifndef _Included_com_xiongliang_ffmpegpratice_DecodeAudio
#define _Included_com_xiongliang_ffmpegpratice_DecodeAudio
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiongliang_ffmpegpratice_DecodeAudio
 * Method:    devodeAudio
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xiongliang_ffmpegpratice_DecodeAudio_devodeAudio
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
